name: "Safe Transaction Checker"
description: "GitHub Action to check Safe transaction state"
author: "rmeissner"
branding:
  icon: "award"
  color: blue
inputs:
  node-url:
    description: "Node url"
  check-target:
    description: "<type>/<id> of the target (e.g. multisig/<safetxhash> or safesnap/<snapshot_ipfs>)"
  show-info:
    description: "Show Safe, target and simulation info"
    default: "true"
  fail-on-safe-storage-changes:
    description: "Fail if the Safe storage is changed"
    default: "true"
  fail-on-unknown-delegatecall:
    description: "Fail if an unknown delegatecall is used"
    default: "true"
  simulate-tx:
    description: "Simulate transaction"
    default: "true"
runs:
  using: "node16"
  main: "lib/index.js"